const APP_LAYOUT_PAGE_TITLES: Partial<Record<string, string>> = {
  dashboard: 'Dashboard',
  prospek: 'Prospek',
  leads: 'Prospek',
  'embed-forms': 'Embed Lead Form',
  'proof-assets': 'Galeri Bukti',
  'master-data': 'Master Data',
  'recurring-expenses': 'Pengeluaran Rutin',
  cashflow: 'Biaya Operasional',
  payroll: 'Payroll & Komisi',
  'payment-gateway': 'Payment Gateway',
  'ads-realtime': 'Integrasi Iklan',
  'ads-monitoring': 'Monitoring Performance',
  'ads-monitoring-workspace': 'Ads Monitoring',
  'ads-monitoring-integrasi-iklan': 'Ads Monitoring / Integrasi Iklan',
  'ads-monitoring-overview': 'Ads Monitoring / Ringkasan',
  'ads-monitoring-advertiser-matrix': 'Ads Monitoring / Matriks Advertiser',
  'ads-monitoring-cs-matrix': 'Ads Monitoring / Matriks CS',
  'ads-monitoring-diagnostics': 'Ads Monitoring / Diagnostik',
  'ads-monitoring-openclaw': 'Ads Monitoring / OpenClaw',
  'ads-monitoring-action-sandbox': 'Ads Monitoring / Simulasi Aksi',
  'conversation-center': 'Pusat Percakapan',
  'conversation-live-inbox': 'Pusat Percakapan / Kotak Masuk Live',
  'conversation-automation': 'Pusat Percakapan / Bot & Automasi',
  'conversation-routing': 'Pusat Percakapan / Routing CS',
  'conversation-history': 'Pusat Percakapan / Riwayat Percakapan',
  'conversation-channel-settings': 'Pusat Percakapan / Pengaturan Channel',
  whatsapp: 'WhatsApp',
  'whatsapp-dashboard': 'WhatsApp / Dashboard',
  'whatsapp-chats': 'WhatsApp / Chats',
  'whatsapp-contacts': 'WhatsApp / Contacts',
  'whatsapp-templates': 'WhatsApp / Templates',
  'whatsapp-broadcasts': 'WhatsApp / Broadcasts',
  'whatsapp-analytics': 'WhatsApp / Analytics',
  'whatsapp-storage': 'WhatsApp / Storage',
  'whatsapp-inbox-settings': 'WhatsApp / Inbox Settings',
  'whatsapp-accounts': 'WhatsApp / Accounts',
  'technician-schedule': 'Jadwal Teknisi',
  inventory: 'Manajemen Stok',
  'inventory-products': 'Manajemen Stok',
  'inventory-transactions': 'Manajemen Stok',
  'inventory-valuation': 'Manajemen Stok',
  'inventory-settings': 'Manajemen Stok',
  orders: 'Pesanan',
  'daily-report': 'Laporan Operasional',
  'cs-okr-report': 'OKR CS',
  'finance-report': 'Laporan Operasional',
  'daily-ads': 'Iklan Harian',
  affiliates: 'Affiliate',
  'wa-templates': 'Template WhatsApp',
  'audit-logs': 'Riwayat Aktivitas',
  roles: 'Role Management',
  profile: 'Profil Saya',
  'teknisi-mobile': 'Area Teknisi',
  'monitoring-activity': 'Aktivitas Teknisi',
};

export function getAppLayoutPageTitle(activeTab: string) {
  return APP_LAYOUT_PAGE_TITLES[activeTab] ?? 'App';
}
