import type { PermissionKey } from '../../data/permissions';

export type AppLayoutTabPermissionRequirement = PermissionKey | PermissionKey[];

export const APP_LAYOUT_TAB_PERMISSIONS: Partial<Record<string, AppLayoutTabPermissionRequirement>> = {
  dashboard: 'dashboard.view',
  'daily-ads': 'ads.view_daily',
  'ads-realtime': 'monitoring.marketing.view',
  affiliates: 'affiliate.view',
  leads: 'leads.view',
  'embed-forms': 'leads.view',
  'proof-assets': 'proof_assets.view',
  prospek: 'leads.view',
  orders: 'order.view',
  schedule: 'schedule.view',
  'daily-report': ['daily_report.view', 'finance_report.view'],
  'cs-okr-report': 'cs_okr.view',
  monitoring: 'monitoring.view',
  'monitoring-activity': 'monitoring.activity_view',
  map: 'map.view_global',
  'recurring-expenses': 'recurring_expenses.view',
  payments: 'payments.view',
  'ads-monitoring': 'monitoring.marketing.view',
  'ads-monitoring-workspace': 'monitoring.marketing.view',
  'ads-monitoring-overview': 'monitoring.marketing.view',
  'ads-monitoring-integrasi-iklan': 'monitoring.marketing.view',
  'ads-monitoring-advertiser-matrix': 'monitoring.marketing.view',
  'ads-monitoring-cs-matrix': 'monitoring.marketing.view',
  'ads-monitoring-diagnostics': 'monitoring.marketing.view',
  'ads-monitoring-openclaw': 'monitoring.marketing.view',
  'ads-monitoring-action-sandbox': 'monitoring.marketing.view',
  'conversation-center': 'leads.view',
  'conversation-live-inbox': 'leads.view',
  'conversation-automation': 'leads.view',
  'conversation-routing': 'leads.view',
  'conversation-history': 'leads.view',
  'conversation-channel-settings': 'leads.view',
  whatsapp: 'whatsapp.view',
  'whatsapp-dashboard': 'whatsapp.view',
  'whatsapp-chats': 'whatsapp.view',
  'whatsapp-contacts': 'whatsapp.view',
  'whatsapp-templates': 'whatsapp.templates.manage',
  'whatsapp-broadcasts': 'whatsapp.broadcast.manage',
  'whatsapp-analytics': 'whatsapp.view',
  'whatsapp-storage': 'whatsapp.view',
  'whatsapp-inbox-settings': 'whatsapp.settings.manage',
  'whatsapp-accounts': 'whatsapp.settings.manage',
  cashflow: 'operational_expenses.view',
  debts: 'debts.view',
  'finance-report': 'finance_report.view',
  payroll: 'payroll.view',
  inventory: 'inventory.view',
  'inventory-products': 'inventory.view',
  'inventory-transactions': 'stock.transaction.view',
  'inventory-valuation': 'stock.valuation.view',
  'inventory-settings': 'stock.settings.manage',
  'master-data': 'master_data.view',
  users: 'users.view',
  'technician-schedule': 'technician_schedule.view',
  'wa-templates': 'wa_template.view',
  'audit-logs': 'audit_logs.view',
  roles: 'role_permissions.view',
  'teknisi-mobile': 'teknisi.view_mobile',
};
