import { Order, ProspectBooking } from '../../../data';

export const mapProspectBookingFromDB = (booking: any): ProspectBooking => ({
  id: booking.id,
  leadId: booking.lead_id,
  orderId: booking.order_id,
  customerName: booking.customer_name,
  customerPhone: booking.customer_phone,
  scheduleDate: booking.schedule_date,
  scheduleTime: booking.schedule_time,
  branchId: booking.branch_id,
  areaId: booking.area_id,
  address: booking.address,
  mapsUrl: booking.maps_url,
  notes: booking.notes,
  status: booking.status,
  csId: booking.cs_id,
  advertiserId: booking.advertiser_id,
  technicianId: booking.technician_id,
  vehicleId: booking.vehicle_id,
  platformId: booking.platform_id,
  subChannelId: booking.sub_channel_id,
  serviceId: booking.service_id,
  createdAt: booking.created_at,
  updatedAt: booking.updated_at,
});

export const mapProspectBookingToDB = (booking: ProspectBooking) => ({
  id: booking.id,
  lead_id: booking.leadId,
  order_id: booking.orderId,
  customer_name: booking.customerName,
  customer_phone: booking.customerPhone,
  schedule_date: booking.scheduleDate,
  schedule_time: booking.scheduleTime,
  branch_id: booking.branchId,
  area_id: booking.areaId,
  address: booking.address,
  maps_url: booking.mapsUrl,
  notes: booking.notes,
  status: booking.status,
  cs_id: booking.csId,
  advertiser_id: booking.advertiserId,
  technician_id: booking.technicianId,
  vehicle_id: booking.vehicleId,
  platform_id: booking.platformId,
  sub_channel_id: booking.subChannelId,
  service_id: booking.serviceId,
  updated_at: booking.updatedAt || new Date().toISOString(),
});

export const mapOrderFromDB = (o: any): Order => ({
  id: o.id,
  leadDate: o.lead_date,
  customerName: o.customer_name,
  customerPhone: o.customer_phone,
  address: o.address,
  serviceDate: o.service_date,
  serviceTime: o.service_time,
  serviceId: o.service_id,
  serviceCategory: o.service_category,
  mapsUrl: o.maps_url,
  vehicleId: o.vehicle_id,
  price: o.price,
  units: o.units || 1,
  platformId: o.platform_id,
  subChannelId: o.sub_channel_id,
  csId: o.cs_id,
  advertiserId: o.advertiser_id,
  technicianId: o.technician_id,
  branchId: o.branch_id,
  areaId: o.area_id,
  status: o.status,
  paymentType: o.payment_type,
  paymentMethodId: o.payment_method_id,
  income: o.income,
  paymentStatus: o.payment_status,
  paymentValidation: o.payment_validation,
  affiliateName: o.affiliate_name,
  lat: o.lat,
  lng: o.lng,
  leadId: o.lead_id,
  templateHistory: o.template_history || [],
  photos: o.photos,
  startTravelAt: o.start_travel_at,
  startWorkAt: o.start_work_at,
  finishedAt: o.finished_at,
  payload: o.payload,
  notes: o.note || o.Note || o.notes || o.keterangan || o.payload?.notes,
  created_at: o.created_at,
  cancelReason: o.cancel_reason,
  cancelReasonNote: o.cancel_reason_note,
  isFollowedUp: o.is_followed_up || false,
  followedUpBy: o.followed_up_by,
  followedUpAt: o.followed_up_at,
  followUpNote: o.follow_up_note,
});

export const mapOrderToDB = (o: Order) => ({
  id: o.id,
  lead_date: o.leadDate,
  customer_name: o.customerName,
  customer_phone: o.customerPhone,
  address: o.address,
  service_date: o.serviceDate,
  service_time: o.serviceTime,
  service_id: o.serviceId,
  service_category: o.serviceCategory,
  maps_url: o.mapsUrl,
  vehicle_id: o.vehicleId,
  price: o.price,
  units: o.units,
  platform_id: o.platformId,
  sub_channel_id: o.subChannelId,
  cs_id: o.csId,
  advertiser_id: o.advertiserId,
  technician_id: o.technicianId,
  branch_id: o.branchId,
  area_id: o.areaId,
  status: o.status,
  payment_type: o.paymentType,
  payment_method_id: o.paymentMethodId,
  income: o.income,
  payment_status: o.paymentStatus,
  payment_validation: o.paymentValidation,
  affiliate_name: o.affiliateName,
  lat: o.lat,
  lng: o.lng,
  lead_id: o.leadId,
  template_history: o.templateHistory,
  photos: o.photos,
  start_travel_at: o.startTravelAt,
  start_work_at: o.startWorkAt,
  finished_at: o.finishedAt,
  payload: o.payload,
  notes: o.notes,
  cancel_reason: o.cancelReason,
  cancel_reason_note: o.cancelReasonNote,
  is_followed_up: o.isFollowedUp,
  followed_up_by: o.followedUpBy,
  followed_up_at: o.followedUpAt,
  follow_up_note: o.followUpNote,
});
